spring:
  application:
    name: microservice-gateway
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring.cloud.gateway:
  discovery:
    locator:
      enabled: true
      lower-case-service-id: true
  routes:
    - id: microservice-courses
      uri: lb://microservice-courses
      predicates:
        - Path=/api/v1/courses/**
      filters:
        - AuthenticationFilter

    - id: microservice-students
      uri: lb://microservice-students
      predicates:
        - Path=/api/v1/students/**
      filters:
        - AuthenticationFilter

    - id: microservices-auth
      uri: lb://microservices-auth
      predicates:
        - Path=/api/v1/auth/**